services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: tasks
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5430:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U myuser -d tasks'" ]
      interval: 10s
      timeout: 3s
      retries: 3
  api:    
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:      
      - '4000:3000'
    environment:
      - PORT=3000
      - NODE_ENV=development
      - DB_USER=myuser
      - DB_HOST=postgres
      - DB_NAME=tasks
      - DB_PASSWORD=qwerty
      - DB_PORT=5432
    command: npm run start
    depends_on:
      - postgres

